class GistController < ApplicationController
  def show
    gist_id = params[:id]
    session[:gist_id] = gist_id
    @transform = Gist.read_gist( gist_id, 'transform.rb', { :access_token => session[:github_token]})
    @source_code = Gist.read_gist( gist_id, 'source.rb', { :access_token => session[:github_token]})
  end


  def create
    source = params[:code]
    transform = params[:transform]
    yml = "v:1\nparser:2.6.3.0\nrails:5.2.3\nruby:2.5.5p157"
    Gist.multi_gist({"source.rb" => source, "transform.rb" => transform, "ruby-ast-explorer.yml" => yml}, 
                    :public => true, 
                    :description => "A Gist generated by ruby-ast-explorer",
                    :access_token => session[:github_token])
    respond_to do |format|
      format.json { render :json => { message: "Exported to gist with name = ruby-ast-explorer.yml successfully." } } 
    end
  end

end
